_wandb:
    value:
        cli_version: 0.23.0
        e:
            dzndpwt2g1u5assdk5jgdwgiebi9cavd:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 32
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "41875931136"
                args:
                    - --dataset
                    - split_mnist
                    - --method
                    - sgd
                    - --num_tasks
                    - "5"
                    - --epochs
                    - "5"
                    - --lr
                    - "1e-3"
                    - --batch_size
                    - "10"
                    - --seed
                    - "42"
                    - --device
                    - mps
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "830267432960"
                email: ishirgarg@berkeley.edu
                executable: /Users/ishirgarg/Github/FOPNG/.venv/bin/python3
                git:
                    commit: 3d25a0c2bd4768ad45d655c063b998f70fb9ec9f
                    remote: https://github.com/ishirgarg/FOPNG
                host: ishirs-mbp.lan
                memory:
                    total: "34359738368"
                os: macOS-14.4.1-arm64-arm-64bit-Mach-O
                program: /Users/ishirgarg/Github/FOPNG/main.py
                python: CPython 3.13.3
                root: /Users/ishirgarg/Github/FOPNG
                startedAt: "2025-11-28T01:11:03.127362Z"
                writerId: dzndpwt2g1u5assdk5jgdwgiebi9cavd
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 41
                - 51
            "2":
                - 1
                - 41
                - 51
            "3":
                - 3
                - 13
                - 16
                - 61
            "4": 3.13.3
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 10
device:
    value: mps
epochs_per_task:
    value: 5
experiment_name:
    value: split_mnist_sgd_5tasks_5epochs_20251127_171055
fopng_epsilon:
    value: 0
fopng_lambda_reg:
    value: 0
grads_per_task:
    value: 200
log_dir:
    value: experiments/split_mnist_sgd_5tasks_5epochs_20251127_171055
lr:
    value: 0.001
save_model:
    value: true
save_plots:
    value: true
save_raw_data:
    value: true
seed:
    value: 42
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: fopng
wandb_tags:
    value: null
